version: '2'
services:
  app:
    build:
      context: .

  repl:
    extends:
      service: app
    ports:
      - "3000:3000"
      - "45380:45380"
    environment:
      - LEIN_REPL_PORT=45380
    volumes:
      - ./project.clj:/schuleinzugsgebiete/project.clj
      - ./src:/schuleinzugsgebiete/src
      - ./resources:/schuleinzugsgebiete/resources
      - ./profiles.clj:/schuleinzugsgebiete/profiles.clj
    command: lein repl :headless

  watch-css:
    extends:
      service: app
    volumes:
      - ./package.json:/schuleinzugsgebiete/package.json
      - ./less:/schuleinzugsgebiete/less
      - ./resources:/schuleinzugsgebiete/resources
    command: npm run-script watch-css

  watch-js:
    extends:
      service: app
    volumes:
      - ./package.json:/schuleinzugsgebiete/package.json
      - ./js:/schuleinzugsgebiete/js
      - ./resources:/schuleinzugsgebiete/resources
    command: npm run-script watch-js
