version: '2'
services:
  app:
    build:
      context: .

  dev:
    extends:
      service: app
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
    volumes:
      - ./package.json:/schuleinzugsgebiete/package.json
      - ./lib:/schuleinzugsgebiete/lib
    command: npm run-script dev

  watch-css:
    extends:
      service: app
    volumes:
      - ./package.json:/schuleinzugsgebiete/package.json
      - ./less:/schuleinzugsgebiete/less
      - ./resources:/schuleinzugsgebiete/resources
    user: root
    command: npm run-script watch-css

  watch-js:
    extends:
      service: app
    volumes:
      - ./package.json:/schuleinzugsgebiete/package.json
      - ./js:/schuleinzugsgebiete/js
      - ./resources:/schuleinzugsgebiete/resources
    user: root
    command: npm run-script watch-js
